name: CI

on:
    pull_request:
        branches:
            - "*"

jobs:
    lint:
        name: Check lint
        runs-on: self-hosted
        container: node:lts
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: install packages
              run: npm i
            - name: run lint
              run: npm run lint

    check-build:
        needs: [lint]
        name: Check Build
        runs-on: self-hosted
        timeout-minutes: 5
        container: node:20-alpine
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: install packages
              run: npm ci
            - name: run build
              run: npm run build
